FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS builder
SHELL ["powershell"]
WORKDIR c:\\app
# ENV MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
# RUN $env:PATH = $env:MSBUILD_PATH + ';' + $env:PATH
COPY . .
RUN msbuild TestingConsole.csproj /p:OutputPath=c:\out

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019
WORKDIR c:\\MYProgram
COPY --from=builder C:\\out .

